#!/usr/bin/env python3
"""Draft mobile-specific test cases (QA Suite compact format) and a device coverage matrix.

Test cases (--out): an always-on core set for every iOS/Android app (install, upgrade with data
migration, reinstall, cold start, background/foreground, process death, low memory, rotation,
multi-window, interruptions, offline, connection loss mid-transaction, slow network, captive
portal, TLS, font scale, screen reader, touch targets/contrast, low storage, dark mode, Turkish
locale, jank, store privacy disclosures) plus sets for the capabilities you name. Platform-specific
variants are emitted per platform (e.g. iOS "Allow Once"/ATT vs Android "Only this time"/background
location). Each case has category, priority, technique (checklist / error guessing), tags
(mobile, android/ios, capability, masvs-*/wcag-*), steps with expected results, and an automation
hint. Review, adapt to the real app, then append to qa/test-cases.src.md and run qa_compact.py.

Device matrix (--devices + --matrix-out): picks, per platform, the mandatory edge devices
(oldest OS version, newest OS version, smallest screen, the top tablet and the top foldable if
listed), then adds the remaining devices in descending share order (ties by name) until the
cumulative share reaches --target-share. "share" is the percentage of THAT platform's active
users (from your analytics). Shares are disjoint, so once the edges are fixed this greedy order
reaches the target with the fewest devices. Deterministic: same input, same output.

devices.json: a list (or {"devices": [...]}) of objects with
  name, os ("android" | "ios"), version ("14", "17.5"), share (number), form_factor
  ("phone" | "tablet" | "foldable"), optional width_dp (logical width in dp/pt, for "smallest screen").

Usage:
  python mobile_checklist.py --platform both --capabilities push,payments,deeplinks,auth \\
      --req REQ-030 --tests qa/test-cases.json --lang tr --out qa/design/mobile.src.md
  python mobile_checklist.py --platform android --devices devices.json --target-share 80 \\
      --matrix-out qa/design/device-matrix.md
  python mobile_checklist.py --list-capabilities
Exit codes: 0 ok, 1 invalid devices file content, 2 usage error or unreadable input.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "assets"
PLATFORMS = ("android", "ios")
FORM_FACTORS = ("phone", "tablet", "foldable")
T = {
    "en": {
        "head": "# Mobile test cases drafted by mobile_checklist.py (platform: {plat}; capabilities: {caps}). "
                "Review, adapt steps to the real app, then append to qa/test-cases.src.md.",
        "head2": "# Run them on the release device matrix and record results per device (see references/mobile-testing.md).",
        "m_title": "# Device coverage matrix",
        "m_src": "Generated by mobile_checklist.py from `{src}`. Share figures are copied from the input: they are only as good as the analytics behind them.",
        "m_algo": "Selection per platform: (1) mandatory edges: oldest OS version, newest OS version, smallest screen, the top tablet and the top foldable if listed; "
                  "(2) then the remaining devices in descending share order (ties by name) until the cumulative share reaches {target}%. "
                  "Shares are disjoint segments, so once the edges are fixed this greedy order reaches the target with the fewest devices.",
        "m_cols": "| # | Device | OS | Form factor | Width (dp/pt) | Share % | Cumulative % | Why |",
        "why": {"oldest": "oldest OS (minimum supported)", "newest": "newest OS", "smallest": "smallest screen",
                "tablet": "tablet", "foldable": "foldable", "share": "share"},
        "m_sum": "**{n} devices cover {cov}% of the listed {plat} user share** (target {target}%, listed total {total}%).",
        "m_warn": "Target not reached: the listed {plat} devices add up to only {total}%. Add rows from your analytics or cover the long tail on a device cloud.",
        "m_rest": "Not in the release matrix (breadth runs on emulators/simulators or a device cloud):",
        "m_none": "none",
        "m_os": "| OS version | Share % | In matrix |",
        "yes": "yes", "no": "no",
        "m_use": ["## How to use",
                  "- Release matrix: run the full mobile checklist on these devices (real devices, own or in a device cloud).",
                  "- Every build: smoke tests on emulators/simulators for the oldest and newest OS.",
                  "- Re-run the selection each quarter, or when the analytics shift by more than a few points."],
    },
    "tr": {
        "head": "# mobile_checklist.py ile taslak mobil test senaryoları (platform: {plat}; yetenekler: {caps}). "
                "Gözden geçirin, adımları gerçek uygulamaya uyarlayın, sonra qa/test-cases.src.md dosyasına ekleyin.",
        "head2": "# Senaryoları sürüm cihaz matrisinde çalıştırın ve sonuçları cihaz bazında kaydedin (bkz. references/mobile-testing.md).",
        "m_title": "# Cihaz kapsama matrisi",
        "m_src": "mobile_checklist.py tarafından `{src}` dosyasından üretildi. Pay değerleri girdiden kopyalanır: arkasındaki analitik veri kadar doğrudur.",
        "m_algo": "Platform başına seçim: (1) zorunlu uç cihazlar: en eski işletim sistemi sürümü, en yeni sürüm, en küçük ekran, listede varsa en yüksek paylı tablet ve katlanabilir; "
                  "(2) ardından kalan cihazlar, kümülatif pay %{target} olana kadar azalan pay sırasıyla (eşitlikte ada göre) eklenir. "
                  "Paylar ayrık dilimler olduğundan, uç cihazlar sabitlendikten sonra bu açgözlü sıra hedefe en az cihazla ulaşır.",
        "m_cols": "| # | Cihaz | İS | Form | Genişlik (dp/pt) | Pay % | Kümülatif % | Neden |",
        "why": {"oldest": "en eski İS (desteklenen en düşük)", "newest": "en yeni İS", "smallest": "en küçük ekran",
                "tablet": "tablet", "foldable": "katlanabilir", "share": "pay"},
        "m_sum": "**{n} cihaz, listelenen {plat} kullanıcı payının %{cov} kadarını kapsar** (hedef %{target}, listelenen toplam %{total}).",
        "m_warn": "Hedefe ulaşılamadı: listelenen {plat} cihazlarının toplamı yalnızca %{total}. Analitikten satır ekleyin veya uzun kuyruğu bir cihaz bulutunda kapsayın.",
        "m_rest": "Sürüm matrisinde olmayanlar (genişlik testleri emülatör/simülatörde veya cihaz bulutunda):",
        "m_none": "yok",
        "m_os": "| İS sürümü | Pay % | Matriste |",
        "yes": "evet", "no": "hayır",
        "m_use": ["## Nasıl kullanılır",
                  "- Sürüm matrisi: mobil kontrol listesinin tamamını bu cihazlarda çalıştırın (kendi cihazlarınız veya cihaz bulutu).",
                  "- Her derleme: en eski ve en yeni İS için emülatör/simülatörde duman (smoke) testleri.",
                  "- Seçimi her çeyrekte veya analitik birkaç puandan fazla değiştiğinde yeniden çalıştırın."],
    },
}
PLAT_NAME = {"android": "Android", "ios": "iOS"}


def load_catalogue() -> dict:
    return json.loads((ASSETS / "mobile-checks.json").read_text(encoding="utf-8"))


def next_id(tests_path: str | None, start: int | None) -> int:
    if start:
        return start
    if tests_path and Path(tests_path).exists():
        data = json.loads(Path(tests_path).read_text(encoding="utf-8-sig"))
        ids = [int(m.group(1)) for t in (data.get("test_cases", []) if isinstance(data, dict) else data)
               if (m := re.match(r"TC-(\d+)", t.get("id", "")))]
        return (max(ids) + 1) if ids else 1
    return 1


def select_checks(cat: dict, platforms: list[str], caps: set[str]) -> list[dict]:
    out = []
    for c in cat["checks"]:
        if c["platform"] != "both" and c["platform"] not in platforms:
            continue
        if "core" in c["caps"] or caps & set(c["caps"]):
            out.append(c)
    return out


def via_text(check: dict, platforms: list[str], lang: str) -> str:
    via = check.get("via_tr" if lang == "tr" else "via") or check.get("via", {})
    plats = [p for p in platforms if p in via and (check["platform"] in ("both", p))]
    if len(plats) == 1:
        return via[plats[0]]
    return "; ".join(f"{PLAT_NAME[p]}: {via[p]}" for p in plats)


def render_checks(cat: dict, checks: list[dict], platforms: list[str], caps: set[str], req: str,
                  lang: str, first: int) -> tuple[list[str], int]:
    t = T[lang]
    lines = [t["head"].format(plat="+".join(platforms), caps=", ".join(["core"] + sorted(caps))), t["head2"]]
    n = first
    for c in checks:
        loc = c[lang]
        tid = f"TC-{n:03d}"
        n += 1
        plat_tags = [p for p in platforms if c["platform"] in ("both", p)]
        cap_tag = "core" if "core" in c["caps"] else next(x for x in c["caps"] if x in caps)
        tags = []
        for tag in ["mobile", *plat_tags, cap_tag, *c.get("tags", [])]:
            if tag not in tags:
                tags.append(tag)
        auto = cat["auto"][c["auto"]]
        lines += ["", f"## {tid} | {loc['title']}",
                  f"req: {req} | pri: {c['pri']} | pol: {c['pol']} | tech: {c['tech']} | cat: {c['cat']}"]
        for p in loc.get("pre", []):
            lines.append(f"pre: {p}")
        via = via_text(c, platforms, lang)
        for i, (act, exp) in enumerate(loc["steps"], 1):
            lines.append(f"{i}. {act.replace('{via}', via)} => {exp.replace('{via}', via)}")
        lines.append(f"tags: {', '.join(tags)} | auto: {'yes' if auto['candidate'] else 'no'}, {auto[lang]} | status: draft")
    questions = []
    for key in ["core", *sorted(caps)]:
        questions += cat.get("questions", {}).get(key, {}).get(lang, [])
    if questions:
        lines.append("")
        lines += [f"# QUESTION: {q}" for q in dict.fromkeys(questions)]
    return lines, n - first


# ---------------------------------------------------------------- device matrix

def version_key(v) -> tuple[int, ...]:
    nums = re.findall(r"\d+", str(v))
    return tuple(int(x) for x in nums) if nums else ()


def validate_devices(raw) -> tuple[list[dict], list[str]]:
    rows = raw.get("devices") if isinstance(raw, dict) else raw
    errors: list[str] = []
    if not isinstance(rows, list) or not rows:
        return [], ["devices file must be a non-empty list, or an object with a non-empty 'devices' list"]
    devices = []
    for i, d in enumerate(rows, 1):
        where = f"device #{i} ({d.get('name', '?') if isinstance(d, dict) else '?'})"
        if not isinstance(d, dict):
            errors.append(f"{where}: not an object")
            continue
        missing = [k for k in ("name", "os", "version", "share") if d.get(k) in (None, "")]
        if missing:
            errors.append(f"{where}: missing {', '.join(missing)}")
            continue
        os_ = str(d["os"]).strip().lower()
        if os_ not in PLATFORMS:
            errors.append(f"{where}: os must be android or ios, got '{d['os']}'")
            continue
        share = d["share"]
        if isinstance(share, bool) or not isinstance(share, (int, float)) or not 0 <= share <= 100:
            errors.append(f"{where}: share must be a number between 0 and 100")
            continue
        ff = str(d.get("form_factor", d.get("formFactor", "phone"))).strip().lower()
        if ff not in FORM_FACTORS:
            errors.append(f"{where}: form_factor must be one of {', '.join(FORM_FACTORS)}")
            continue
        if not version_key(d["version"]):
            errors.append(f"{where}: version '{d['version']}' has no number")
            continue
        width = d.get("width_dp")
        if width is not None and (isinstance(width, bool) or not isinstance(width, (int, float)) or width <= 0):
            errors.append(f"{where}: width_dp must be a positive number")
            continue
        devices.append({"name": str(d["name"]), "os": os_, "version": str(d["version"]), "share": float(share),
                        "form_factor": ff, "width_dp": width})
    for p in PLATFORMS:
        total = sum(d["share"] for d in devices if d["os"] == p)
        if total > 100.5:
            errors.append(f"{p}: shares add up to {total:.1f}% (> 100); 'share' is the percentage of this platform's users")
    return devices, errors


def select_devices(devs: list[dict], target: float) -> list[tuple[dict, list[str]]]:
    """Deterministic greedy selection: mandatory edges first, then descending share until the target."""
    chosen: dict[str, list[str]] = {}
    order: list[dict] = []

    def take(cands: list[dict], reason: str):
        if not cands:
            return
        best = sorted(cands, key=lambda d: (d["name"] not in chosen, -d["share"], d["name"]))[0]
        if best["name"] not in chosen:
            chosen[best["name"]] = []
            order.append(best)
        chosen[best["name"]].append(reason)

    vmin = min(version_key(d["version"]) for d in devs)
    vmax = max(version_key(d["version"]) for d in devs)
    take([d for d in devs if version_key(d["version"]) == vmin], "oldest")
    take([d for d in devs if version_key(d["version"]) == vmax], "newest")
    widths = [d for d in devs if d["width_dp"] and d["form_factor"] == "phone"] or [d for d in devs if d["width_dp"]]
    if widths:
        wmin = min(d["width_dp"] for d in widths)
        take([d for d in widths if d["width_dp"] == wmin], "smallest")
    take([d for d in devs if d["form_factor"] == "tablet"], "tablet")
    take([d for d in devs if d["form_factor"] == "foldable"], "foldable")
    covered = sum(d["share"] for d in order)
    for d in sorted(devs, key=lambda d: (-d["share"], d["name"])):
        if covered >= target - 1e-9:
            break
        if d["name"] in chosen:
            continue
        chosen[d["name"]] = ["share"]
        order.append(d)
        covered += d["share"]
    return [(d, chosen[d["name"]]) for d in order]


def fmt(x: float) -> str:
    return f"{x:.1f}"


def build_matrix(devices: list[dict], platforms: list[str], target: float, lang: str, src: str) -> tuple[str, list[str]]:
    t = T[lang]
    lines = [t["m_title"], "", t["m_src"].format(src=src), "", t["m_algo"].format(target=fmt(target))]
    warnings = []
    for p in platforms:
        devs = [d for d in devices if d["os"] == p]
        if not devs:
            continue
        sel = select_devices(devs, target)
        total = sum(d["share"] for d in devs)
        lines += ["", f"## {PLAT_NAME[p]}", "", t["m_cols"], "|---|---|---|---|---|---|---|---|"]
        cum = 0.0
        for i, (d, reasons) in enumerate(sel, 1):
            cum += d["share"]
            why = ", ".join(t["why"][r] for r in reasons)
            width = fmt(d["width_dp"]).removesuffix(".0") if d["width_dp"] else "-"
            lines.append(f"| {i} | {d['name']} | {PLAT_NAME[p]} {d['version']} | {d['form_factor']} | {width} | "
                         f"{fmt(d['share'])} | {fmt(cum)} | {why} |")
        lines += ["", t["m_sum"].format(n=len(sel), cov=fmt(cum), plat=PLAT_NAME[p], target=fmt(target), total=fmt(total))]
        if cum < target - 1e-9:
            w = t["m_warn"].format(plat=PLAT_NAME[p], total=fmt(total))
            warnings.append(w)
            lines += ["", f"> {w}"]
        names = {d["name"] for d, _ in sel}
        rest = sorted((d for d in devs if d["name"] not in names), key=lambda d: (-d["share"], d["name"]))
        lines += ["", t["m_rest"] + " " + ("; ".join(f"{d['name']} ({PLAT_NAME[p]} {d['version']}, {fmt(d['share'])}%)"
                                                     for d in rest) or t["m_none"])]
        by_ver: dict[str, float] = {}
        major = {}
        for d in devs:
            key = str(version_key(d["version"])[0])
            by_ver[key] = by_ver.get(key, 0.0) + d["share"]
            major.setdefault(key, False)
            if d["name"] in names:
                major[key] = True
        lines += ["", t["m_os"], "|---|---|---|"]
        for key in sorted(by_ver, key=lambda k: int(k), reverse=True):
            lines.append(f"| {PLAT_NAME[p]} {key} | {fmt(by_ver[key])} | {t['yes'] if major[key] else t['no']} |")
    lines += [""] + t["m_use"]
    return "\n".join(lines) + "\n", warnings


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--platform", choices=["ios", "android", "both"], default="both")
    ap.add_argument("--capabilities", default="", help="comma-separated capabilities (see --list-capabilities), or 'all'; core checks are always included")
    ap.add_argument("--list-capabilities", action="store_true")
    ap.add_argument("--req", default="", help="requirement ID(s) the generated tests trace to (required with --out)")
    ap.add_argument("--tests", help="existing test-cases.json to continue TC numbering")
    ap.add_argument("--start", type=int, help="first TC number (overrides --tests)")
    ap.add_argument("--lang", choices=["tr", "en"], default="en")
    ap.add_argument("--out", help="compact test cases (.src.md)")
    ap.add_argument("--devices", help="devices.json with per-platform user share (see assets/devices-example.json)")
    ap.add_argument("--matrix-out", dest="matrix_out", help="device coverage matrix (.md)")
    ap.add_argument("--target-share", dest="target_share", type=float, default=80.0, help="cumulative share per platform to reach (default 80)")
    sys.stdout.reconfigure(encoding="utf-8")
    a = ap.parse_args()
    cat = load_catalogue()
    if a.list_capabilities:
        for k, v in cat["capabilities"].items():
            print(f"{k:12s} {v[a.lang]}")
        return 0
    if not a.out and not a.matrix_out:
        print("error: nothing to do: give --out (test cases) and/or --devices with --matrix-out", file=sys.stderr)
        return 2
    if bool(a.devices) != bool(a.matrix_out):
        print("error: --devices and --matrix-out go together", file=sys.stderr)
        return 2
    if not 0 < a.target_share <= 100:
        print("error: --target-share must be in (0, 100]", file=sys.stderr)
        return 2
    platforms = list(PLATFORMS) if a.platform == "both" else [a.platform]
    raw_caps = {c.strip().lower() for c in a.capabilities.split(",") if c.strip()}
    caps = set(cat["capabilities"]) if "all" in raw_caps else raw_caps
    unknown = caps - set(cat["capabilities"])
    if unknown:
        print(f"error: unknown capabilities {sorted(unknown)}; use --list-capabilities", file=sys.stderr)
        return 2
    if a.out:
        if not a.req:
            print("error: --req is required with --out so the generated tests are traceable", file=sys.stderr)
            return 2
        checks = select_checks(cat, platforms, caps)
        lines, count = render_checks(cat, checks, platforms, caps, a.req, a.lang, next_id(a.tests, a.start))
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"wrote {a.out}: {count} test cases ({'+'.join(platforms)}; core + {', '.join(sorted(caps)) or 'no capabilities'})")
    if a.matrix_out:
        try:
            raw = json.loads(Path(a.devices).read_text(encoding="utf-8-sig"))
        except (OSError, ValueError) as e:
            print(f"error: cannot read {a.devices}: {e}", file=sys.stderr)
            return 2
        devices, errors = validate_devices(raw)
        if errors:
            for e in errors:
                print(f"error: {e}", file=sys.stderr)
            return 1
        md, warnings = build_matrix(devices, platforms, a.target_share, a.lang, Path(a.devices).name)
        Path(a.matrix_out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.matrix_out).write_text(md, encoding="utf-8", newline="\n")
        print(f"wrote {a.matrix_out}: device matrix for {'+'.join(platforms)} (target {fmt(a.target_share)}%)")
        for w in warnings:
            print(f"warning: {w}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
