#!/usr/bin/env python3
"""Generate a k6 load-test script whose thresholds come straight from a performance requirement.

k6 exits non-zero (99) when a threshold fails, so the requirement becomes a pass/fail gate in CI.

Spec (JSON):
{
  "id": "DS-010", "title": "Kupon doğrulama performansı", "requirement_ids": ["REQ-006"], "test_id": "TC-027",
  "base_url": "https://staging.example.com",            # overridable with -e BASE_URL=...
  "profile": "load",                                     # smoke | load | stress | spike | soak
  "target": {"type": "arrival-rate", "rate": 50},        # requests (iterations) per second, or {"type": "vus", "vus": 200}
  "duration": "10m", "ramp": "2m",
  "thresholds": {"p95_ms": 800, "p99_ms": 1500, "error_rate": 0.01, "checks_rate": 0.99},
  "auth": {"type": "bearer", "env": "K6_TOKEN"},         # optional; token read from environment, never stored
  "think_time_s": 1,
  "requests": [
    {"name": "apply_coupon", "method": "POST", "path": "/api/cart/coupon", "json": {"code": "YAZ10"},
     "expect_status": 200, "thresholds": {"p95_ms": 800}}
  ]
}
Requests run in order per iteration (a user journey). Per-request thresholds override the global ones.

Usage:
  python generate_k6.py qa/design/DS-010-coupon-perf.json --out perf/DS-010.k6.js
  k6 run -e BASE_URL=https://staging.example.com perf/DS-010.k6.js      # exit 99 = threshold failed
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

DUR = re.compile(r"^(\d+)(s|m|h)$")


def seconds(d: str) -> int:
    m = DUR.match(str(d))
    if not m:
        raise ValueError(f"duration must look like 30s, 10m or 2h: {d!r}")
    return int(m.group(1)) * {"s": 1, "m": 60, "h": 3600}[m.group(2)]


def fmt(sec: int) -> str:
    return f"{sec // 3600}h" if sec % 3600 == 0 and sec >= 3600 else f"{sec // 60}m" if sec % 60 == 0 else f"{sec}s"


def stages(profile: str, peak: int, duration: str, ramp: str) -> list[tuple[str, int]]:
    d, r = seconds(duration), seconds(ramp)
    if profile == "smoke":
        return [("1m", max(1, min(peak, 2)))]
    if profile == "load":
        return [(fmt(r), peak), (fmt(d), peak), (fmt(max(r // 2, 30)), 0)]
    if profile == "stress":
        steps = [max(1, peak // 2), peak, int(peak * 1.5), peak * 2]
        out = []
        for s in steps:
            out += [(fmt(r), s), (fmt(max(d // 4, 60)), s)]
        return out + [(fmt(r), 0)]
    if profile == "spike":
        return [(fmt(r), peak), (fmt(max(d // 3, 60)), peak), ("10s", peak * 5), ("1m", peak * 5),
                ("10s", peak), (fmt(max(d // 3, 60)), peak), ("30s", 0)]
    if profile == "soak":
        return [(fmt(r), peak), (fmt(max(d, 3600)), peak), (fmt(r), 0)]
    raise ValueError(f"unknown profile {profile!r}")


def js(v) -> str:
    return json.dumps(v, ensure_ascii=False)


def build(spec: dict) -> str:
    th = spec.get("thresholds", {})
    target = spec.get("target", {"type": "vus", "vus": 10})
    profile = spec.get("profile", "load")
    arrival = target.get("type") == "arrival-rate"
    peak = int(target.get("rate" if arrival else "vus", 10))
    st = stages(profile, peak, spec.get("duration", "10m"), spec.get("ramp", "2m"))
    stage_js = ",\n".join(f"        {{ duration: {js(d)}, target: {t} }}" for d, t in st)
    if arrival:
        executor = (f"      executor: 'ramping-arrival-rate',\n      startRate: 0,\n      timeUnit: '1s',\n"
                    f"      preAllocatedVUs: {max(peak * 2, 5)},\n      maxVUs: {max(peak * 10, 20)},\n")
    else:
        executor = "      executor: 'ramping-vus',\n      startVUs: 0,\n"
    thresholds = {}
    if th.get("error_rate") is not None:
        thresholds["http_req_failed"] = [f"rate<{th['error_rate']}"]
    if th.get("checks_rate") is not None:
        thresholds["checks"] = [f"rate>{th['checks_rate']}"]
    for r in spec["requests"]:
        rt = {**th, **r.get("thresholds", {})}
        lim = []
        if rt.get("p95_ms") is not None:
            lim.append(f"p(95)<{rt['p95_ms']}")
        if rt.get("p99_ms") is not None:
            lim.append(f"p(99)<{rt['p99_ms']}")
        if lim:
            thresholds[f"http_req_duration{{name:{r['name']}}}"] = lim
    th_js = ",\n".join(f"    {js(k)}: {js(v)}" for k, v in thresholds.items())
    reqs = ",".join(spec.get("requirement_ids", []))
    auth = spec.get("auth") or {}
    lines = [
        f"// Generated by QA Suite (generate_k6.py) from {spec.get('id', '')} {spec.get('title', '')}".rstrip(),
        f"// Requirements: {reqs or '-'} · test case: {spec.get('test_id', '-')} · profile: {profile}",
        "// Run: k6 run -e BASE_URL=<test environment> <this file>   (exit code 99 = a threshold failed)",
        "// Only run against environments you own and are allowed to load-test; never against production without approval.",
        "import http from 'k6/http';",
        "import { check, sleep } from 'k6';",
        "",
        f"const BASE_URL = __ENV.BASE_URL || {js(spec.get('base_url', 'http://localhost:3000'))};",
    ]
    if auth.get("type") == "bearer":
        lines.append(f"const TOKEN = __ENV.{auth.get('env', 'K6_TOKEN')};")
    lines += ["", "export const options = {",
              f"  tags: {{ testid: {js(spec.get('id', 'perf'))}, requirements: {js(reqs)} }},",
              "  scenarios: {", f"    {re.sub(r'[^A-Za-z0-9_]', '_', profile)}: {{", executor + "      stages: [",
              stage_js, "      ],", "    },", "  },", "  thresholds: {", th_js, "  },", "};", "",
              "export default function () {"]
    headers = "{ 'Content-Type': 'application/json'" + (", Authorization: `Bearer ${TOKEN}`" if auth.get("type") == "bearer" else "") + " }"
    for r in spec["requests"]:
        method = r.get("method", "GET").upper()
        url = f"`${{BASE_URL}}{r['path']}`"
        params = f"{{ headers: {headers}, tags: {{ name: {js(r['name'])} }} }}"
        body = js(json.dumps(r["json"], ensure_ascii=False)) if "json" in r else "null"
        call = (f"http.get({url}, {params})" if method == "GET"
                else f"http.request({js(method)}, {url}, {body}, {params})")
        lines += [f"  const {r['name']} = {call};",
                  f"  check({r['name']}, {{ {js(r['name'] + ' status ' + str(r.get('expect_status', 200)))}: "
                  f"(res) => res.status === {int(r.get('expect_status', 200))} }});"]
    lines += [f"  sleep({spec.get('think_time_s', 1)});", "}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("spec")
    ap.add_argument("--out")
    a = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    try:
        spec = json.loads(Path(a.spec).read_text(encoding="utf-8-sig"))
        if not spec.get("requests"):
            raise ValueError("spec needs at least one request")
        text = build(spec)
    except (OSError, ValueError, KeyError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    if a.out:
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {a.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
