// Generated by QA Suite (generate_specs.py) from test-cases.json; implemented against the demo app (black-box).
import { test, expect } from "./fixtures";
import { MSG } from "../pages/FastTransferPage";

test.describe("REQ-006 5.000,00 TL'yi aşan transferlerde 5,00 TL işlem ücreti", () => {

  test("TC-020 5.000,00 TL'de (ücret eşiği) ücret alınmaz", {
    tag: ["@TC-020", "@REQ-006", "@REQ-007", "@high", "@regression"],
    annotation: [{ type: "qa_id", description: "TC-020" }, { type: "requirements", description: "BANK-310" }],
  }, async ({ fast }) => {
    await test.step("1. 'Tutar (TL)' alanına tutarı yaz, 'Devam'a tıkla", async () => {
      await fast.submit({ amount: "5.000,00" });
      await expect(fast.alert).toHaveText(MSG.success);
    });
    await test.step("2. 'Dekont' bölümünü incele", async () => {
      await expect(fast.receiptAmount).toHaveText("5.000,00 TL");
      await expect(fast.receiptFee).toHaveText("0,00 TL");
      await expect(fast.receiptTotal).toHaveText("5.000,00 TL");
    });
    await test.step("3. Bakiyeyi incele", async () => {
      await expect(fast.balance).toHaveText("115.000,00 TL");
    });
  });

  test("TC-021 5.000,01 TL'de 5,00 TL ücret alınır; bakiye ve limit doğru düşer", {
    tag: ["@TC-021", "@REQ-006", "@REQ-007", "@REQ-016", "@high", "@smoke", "@regression"],
    annotation: [{ type: "qa_id", description: "TC-021" }, { type: "requirements", description: "BANK-310" }],
  }, async ({ fast }) => {
    await test.step("1. 'Tutar (TL)' alanına tutarı yaz, 'Devam'a tıkla", async () => {
      await fast.submit({ amount: "5.000,01" });
      await expect(fast.alert).toHaveText(MSG.success);
    });
    await test.step("2. 'Dekont' bölümünü incele", async () => {
      await expect(fast.receiptAmount).toHaveText("5.000,01 TL");
      await expect(fast.receiptFee).toHaveText("5,00 TL");
      await expect(fast.receiptTotal).toHaveText("5.005,01 TL");
    });
    await test.step("3. Bakiye ve kalan limiti incele", async () => {
      await expect(fast.balance).toHaveText("114.994,99 TL");
      await expect(fast.dailyRemaining).toHaveText("94.999,99 TL");
    });
  });
});
