// Generated by QA Suite (generate_specs.py) from test-cases.json; implemented against the demo app (black-box).
import { test, expect } from "./fixtures";
import { MSG } from "../pages/FastTransferPage";

test.describe("REQ-002 İşlem başına azami tutar 50.000,00 TL", () => {

  test("TC-003 50.000,00 TL (işlem üst sınırı) SMS doğrulama ile gerçekleşir", {
    tag: ["@TC-003", "@REQ-002", "@REQ-005", "@high", "@smoke", "@regression"],
    annotation: [{ type: "qa_id", description: "TC-003" }, { type: "requirements", description: "BANK-310" }],
  }, async ({ fast }) => {
    await test.step("1. 'Tutar (TL)' alanına tutarı yaz, 'Devam'a tıkla", async () => {
      await fast.submit({ amount: "50.000,00" });
      await expect(fast.alert).toHaveText(MSG.otpRequired);
      await expect(fast.otpStep).toBeVisible();
    });
    await test.step("2. 'SMS kodu' alanına kodu yaz, 'Onayla'ya tıkla", async () => {
      await fast.confirmOtp("123456");
      await expect(fast.alert).toHaveText(MSG.success);
      await expect(fast.receiptAmount).toHaveText("50.000,00 TL");
      await expect(fast.receiptFee).toHaveText("5,00 TL");
      await expect(fast.receiptTotal).toHaveText("50.005,00 TL");
    });
    await test.step("3. Bakiye ve kalan limiti incele", async () => {
      await expect(fast.balance).toHaveText("69.995,00 TL");
      await expect(fast.dailyRemaining).toHaveText("50.000,00 TL");
    });
  });

  test("TC-004 50.000,01 TL (işlem üst sınırının üstü) reddedilir", {
    tag: ["@TC-004", "@REQ-002", "@high", "@regression"],
    annotation: [{ type: "qa_id", description: "TC-004" }, { type: "requirements", description: "BANK-310" }],
  }, async ({ fast }) => {
    await test.step("1. 'Tutar (TL)' alanına tutarı yaz, 'Devam'a tıkla", async () => {
      await fast.submit({ amount: "50.000,01" });
      await expect(fast.alert).toHaveText(MSG.max);
      await expect(fast.otpStep).toBeHidden();
      await expect(fast.receipt).toBeHidden();
    });
    await test.step("2. Bakiye ve kalan limiti incele", async () => {
      await fast.expectNoTransfer("120.000,00 TL", "100.000,00 TL");
    });
  });
});
