// Generated by QA Suite (testing-apis/openapi_tests.py). Same TC IDs as the compact test cases.
// Env: API_BASE_URL, API_TOKEN, API_TOKEN_OTHER (optional). Test accounts only.
import { test, expect } from '@playwright/test';
import { api, checkSchema } from './api-helpers';

test.describe("GET /accounts", () => {
  test("TC-001 GET /accounts geçerli istekle 200 döner ve yanıt şemaya uyar", { tag: ['@TC-001', '@api', '@smoke'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts", {}, { body: null });
    expect(res.status()).toBe(200);
    expect(checkSchema(await res.json(), {"type": "array", "items": {"type": "object", "required": ["id", "iban", "currency", "balance"], "properties": {"id": {"type": "string"}, "iban": {"type": "string"}, "currency": {"type": "string", "enum": ["TRY", "EUR"]}, "balance": {"type": "number"}}}})).toEqual([]);
  });
  test("TC-002 GET /accounts kimlik bilgisi olmadan 401 döner", { tag: ['@TC-002', '@api', '@security'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts", {}, { body: null, auth: false });
    expect(res.status()).toBe(401);
  });
  test("TC-003 GET /accounts 'Bearer' şeması olmayan Authorization başlığını 401 ile reddeder", { tag: ['@TC-003', '@api', '@security'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts", {}, { body: null, auth: false, headers: { Authorization: process.env.API_TOKEN ?? '' } });
    expect(res.status()).toBe(401);
  });
});

test.describe("GET /accounts/{accountId}", () => {
  test("TC-004 GET /accounts/{accountId} geçerli istekle 200 döner ve yanıt şemaya uyar", { tag: ['@TC-004', '@api', '@smoke'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts/{accountId}", {"accountId": "A-100"}, { body: null });
    expect(res.status()).toBe(200);
    expect(checkSchema(await res.json(), {"type": "object", "required": ["id", "iban", "currency", "balance"], "properties": {"id": {"type": "string"}, "iban": {"type": "string"}, "currency": {"type": "string", "enum": ["TRY", "EUR"]}, "balance": {"type": "number"}}})).toEqual([]);
  });
  test("TC-005 GET /accounts/{accountId} kimlik bilgisi olmadan 401 döner", { tag: ['@TC-005', '@api', '@security'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts/{accountId}", {"accountId": "A-100"}, { body: null, auth: false });
    expect(res.status()).toBe(401);
  });
  test("TC-006 GET /accounts/{accountId} olmayan kaynak için 404 döner", { tag: ['@TC-006', '@api'] }, async ({ request }) => {
    const res = await api(request, "GET", "/accounts/{accountId}", {"accountId": "does-not-exist-000"}, { body: null });
    expect(res.status()).toBe(404);
  });
  test("TC-007 GET /accounts/{accountId} başka kullanıcının kaynağına erişimi reddeder (BOLA)", { tag: ['@TC-007', '@api', '@security'] }, async ({ request }) => {
    // A-100 belongs to API_TOKEN (alice), confirmed with GET /accounts; API_TOKEN_OTHER = bob.
    const res = await api(request, "GET", "/accounts/{accountId}", {"accountId": "A-100"}, { body: null, as: 'other' });
    const body = await res.text();
    expect([403, 404], body).toContain(res.status());
    expect(body).not.toContain('TR120006200000000000000100');
  });
});

test.describe("POST /transfers", () => {
  test("TC-008 POST /transfers geçerli istekle 201 döner ve yanıt şemaya uyar", { tag: ['@TC-008', '@api', '@smoke'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(201);
    expect(checkSchema(await res.json(), {"type": "object", "required": ["id", "status", "amount", "currency"], "properties": {"id": {"type": "string"}, "status": {"type": "string", "enum": ["COMPLETED", "PENDING", "REJECTED"]}, "amount": {"type": "number"}, "currency": {"type": "string"}, "fromAccountId": {"type": "string"}, "toIban": {"type": "string"}, "description": {"type": "string"}}})).toEqual([]);
  });
  test("TC-009 POST /transfers kimlik bilgisi olmadan 401 döner", { tag: ['@TC-009', '@api', '@security'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "Kira"}, auth: false });
    expect(res.status()).toBe(401);
  });
  test("TC-010 POST /transfers zorunlu 'fromAccountId' eksikken 400 döner", { tag: ['@TC-010', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-011 POST /transfers zorunlu 'toIban' eksikken 400 döner", { tag: ['@TC-011', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "amount": 100.0, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-012 POST /transfers zorunlu 'amount' eksikken 400 döner", { tag: ['@TC-012', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-013 POST /transfers zorunlu 'currency' eksikken 400 döner", { tag: ['@TC-013', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-014 POST /transfers 'fromAccountId' yanlış tipte (12345) reddedilir", { tag: ['@TC-014', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": 12345, "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-015 POST /transfers 'toIban' yanlış tipte (12345) reddedilir", { tag: ['@TC-015', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": 12345, "amount": 100.0, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-016 POST /transfers 'amount' = 1 (sınır, geçerli) kabul edilir", { tag: ['@TC-016', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 1, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(201);
  });
  test("TC-017 POST /transfers 'amount' = 0.99 (alt sınırın altı) reddedilir", { tag: ['@TC-017', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 0.99, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-018 POST /transfers 'amount' = 50000 (sınır, geçerli) kabul edilir", { tag: ['@TC-018', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 50000, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(201);
  });
  test("TC-019 POST /transfers 'amount' = 50000.01 (üst sınırın üstü) reddedilir", { tag: ['@TC-019', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 50000.01, "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-021 POST /transfers 'currency' geçersiz enum değeriyle reddedilir", { tag: ['@TC-021', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "__invalid__", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-022 POST /transfers 'currency' yanlış tipte (12345) reddedilir", { tag: ['@TC-022', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": 12345, "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
  test("TC-023 POST /transfers 'description' = \"aaaaaaaaa…(140 chars)\" (sınır, geçerli) kabul edilir", { tag: ['@TC-023', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"} });
    expect(res.status()).toBe(201);
  });
  test("TC-024 POST /transfers 'description' = \"aaaaaaaaa…(141 chars)\" (en uzun uzunluğun üstü) reddedilir", { tag: ['@TC-024', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"} });
    expect(res.status()).toBe(400);
  });
  test("TC-025 POST /transfers 'description' yanlış tipte (12345) reddedilir", { tag: ['@TC-025', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 100.0, "currency": "TRY", "description": 12345} });
    expect(res.status()).toBe(400);
  });
});

test.describe("GET /transfers/{transferId}", () => {
  test("TC-026 GET /transfers/{transferId} geçerli istekle 200 döner ve yanıt şemaya uyar", { tag: ['@TC-026', '@api', '@smoke'] }, async ({ request }) => {
    // Test data: the OpenAPI example T-1 does not exist in the environment, so create a 1 TRY transfer of API_TOKEN first.
    const created = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 1, "currency": "TRY", "description": "TC-026"} });
    expect(created.ok(), await created.text()).toBe(true); // precondition only: 2xx (201 itself is checked by TC-008)
    const id = (await created.json()).id;
    const res = await api(request, "GET", "/transfers/{transferId}", {"transferId": id}, { body: null });
    expect(res.status()).toBe(200);
    expect(checkSchema(await res.json(), {"type": "object", "required": ["id", "status", "amount", "currency"], "properties": {"id": {"type": "string"}, "status": {"type": "string", "enum": ["COMPLETED", "PENDING", "REJECTED"]}, "amount": {"type": "number"}, "currency": {"type": "string"}, "fromAccountId": {"type": "string"}, "toIban": {"type": "string"}, "description": {"type": "string"}}})).toEqual([]);
  });
  test("TC-027 GET /transfers/{transferId} kimlik bilgisi olmadan 401 döner", { tag: ['@TC-027', '@api', '@security'] }, async ({ request }) => {
    const res = await api(request, "GET", "/transfers/{transferId}", {"transferId": "T-1"}, { body: null, auth: false });
    expect(res.status()).toBe(401);
  });
  test("TC-028 GET /transfers/{transferId} olmayan kaynak için 404 döner", { tag: ['@TC-028', '@api'] }, async ({ request }) => {
    const res = await api(request, "GET", "/transfers/{transferId}", {"transferId": "does-not-exist-000"}, { body: null });
    expect(res.status()).toBe(404);
  });
  test("TC-029 GET /transfers/{transferId} başka kullanıcının kaynağına erişimi reddeder (BOLA)", { tag: ['@TC-029', '@api', '@security'] }, async ({ request }) => {
    // Test data: create a transfer owned by API_TOKEN (alice, A-100), then request it as API_TOKEN_OTHER (bob).
    const created = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": 1, "currency": "TRY", "description": "TC-029"} });
    expect(created.ok(), await created.text()).toBe(true); // precondition only: 2xx (201 itself is checked by TC-008)
    const id = (await created.json()).id;
    const res = await api(request, "GET", "/transfers/{transferId}", {"transferId": id}, { body: null, as: 'other' });
    const body = await res.text();
    expect([403, 404], body).toContain(res.status());
    expect(body).not.toContain('TC-029');
  });
});

// Moved last on purpose: a wrongly accepted non-numeric amount could corrupt the source balance and break later tests.
test.describe("POST /transfers (tip hatası, en son)", () => {
  test("TC-020 POST /transfers 'amount' yanlış tipte (\"abc\") reddedilir", { tag: ['@TC-020', '@api'] }, async ({ request }) => {
    const res = await api(request, "POST", "/transfers", {}, { body: {"fromAccountId": "A-100", "toIban": "TR330006100519786457841326", "amount": "abc", "currency": "TRY", "description": "Kira"} });
    expect(res.status()).toBe(400);
  });
});
