import { defineConfig, devices } from '@playwright/test';

/**
 * Generated by QA Suite (automating-with-playwright).
 * Environment: BASE_URL, TEST_USER, TEST_PASSWORD (see .env.example). Never commit real credentials.
 */
const baseURL = process.env.BASE_URL ?? '{{BASE_URL}}';
const hasLogin = Boolean(process.env.TEST_USER && process.env.TEST_PASSWORD);

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  timeout: 30_000,
  expect: { timeout: 5_000 },
  reporter: [
    ['list'],
    ['html', { open: 'never' }],
    // test-results/results.json feeds QA Suite: python pw_results.py -> qa/results.json -> RTM
    ['json', { outputFile: 'test-results/results.json' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
    // Xray: npm i -D @xray-app/playwright-junit-reporter, then uncomment (uses test_key annotations)
    // ['@xray-app/playwright-junit-reporter', { outputFile: 'test-results/xray-junit.xml', embedAnnotationsAsProperties: true }],
  ],
  use: {
    baseURL,
    locale: '{{LOCALE}}',
    timezoneId: '{{TIMEZONE}}',
    testIdAttribute: 'data-testid',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    // Logs in once and stores the session; skipped automatically when no credentials are set.
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], storageState: hasLogin ? '.auth/user.json' : undefined },
      dependencies: hasLogin ? ['setup'] : [],
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'], storageState: hasLogin ? '.auth/user.json' : undefined },
      dependencies: hasLogin ? ['setup'] : [],
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'], storageState: hasLogin ? '.auth/user.json' : undefined },
      dependencies: hasLogin ? ['setup'] : [],
    },
    // Mobile projects: enable when the pairwise design includes mobile rows.
    // { name: 'mobile-chrome', use: { ...devices['Pixel 7'] } },
    // { name: 'mobile-safari', use: { ...devices['iPhone 15'] } },
  ],
  // Start the app under test locally (optional):
  // webServer: { command: 'npm run start', url: baseURL, reuseExistingServer: !process.env.CI },
});
